const INPUT_ID = {
    torso: "torso",
    head1: "head1",
    head2: "head2",
    leftArm: "leftArm",
    rightArm: "rightArm",
    leftLeg: "leftLeg",
    rightLeg: "rightLeg",
    withShading: "withShading",
    rotateCamera: "rotateCamera",
    cameraRadius: "cameraRadius",
    torso2: "torso2",
    headInsect: "headInsect",
    leftFront: "leftFront",
    rightFront: "rightFront",
    leftBack: "leftBack",
    rightBack: "rightBack",
    tail: "tail",
    torso3 : "torso3",
    globalRotation : "globalRotation",
    posx : "posx",
    posy : "posy",
    headLtoR : "headLtoR",
    headUtoD : "headUtoD",
    neck : "neck",
    frontLfoot : "frontLfoot",
    frontLleg : "frontLleg",
    frontRleg : "frontRleg",
    frontRfoot : "frontRfoot",
    backLleg : "backLleg",
    backLfoot : "backLfoot",
    backRleg : "backRleg",
    backRfoot : "backRfoot"
}